### ISSUE TITLE
Disable log output

### ISSUE THREAD

**Issue by clintberry** [marcello3d/node-mongolian#10]
Is there a way to disable all console.log/info/error output? my log file is getting big... :-)

**Comment by marcello3d** [comment]
Currently you can reassign the log methods:
var mongolian = new Mongolian
mongolian.log.debug = function(){}
mongolian.log.info = function(){}
mongolian.log.warn = function(){}
mongolian.log.error = function(){}

The next version will likely move this to the options object, but I haven't decided on the api yet.

**Comment by clintberry** [comment]
You are the man. Thanks.
