### ISSUE TITLE
Updating embedded objects

### ISSUE THREAD

**Issue by fend25** [marcello3d/node-mongolian#119]
I have a document like this: `{name: 'myDoc', nestedDoc: {a: 1, b: 20, c: 30, d: 40}}`, and I want update some field in nestedDoc, for example, 'a'.
In mongoshell I can use quoted property path:
`db.collection.update({name: 'myDoc'}, {$set: {"nestedDoc.a": 3}})`

But in node.js using mongolian it doesn't work (or I'm doing something wrong):

``` js
var query = {};
var fieldName = 'a';
query['nestedDoc.' + fieldName] = 3;
console.log(query);
db.collection('collection').update({name: 'myDoc'}, {$set: query}, 
  function(err, result) {
    console.log('err: ', err);
    console.log('result: ', result);
});
```

In console I get:

```
{ 'nestedDoc.a': 3 }
err:  null
result:  0
```

**Comment by yorkie** [comment]
Wow, that's really a little careless under using this library, then are you running the same command with the same collection, db or documents, I means you can add the last 2 arguments in update function with true, try to do this.

``` javascript
coll.update({name: 'myDoc', {'$set':query}, true, true, callback);
```

Anyway, give me more details on your problem, my nested documents update command in Mongolian is running on so much servers.
cc @fend25

**Comment by fend25** [comment]
@yorkie
Thank you, it works!))
With `false, false` flags it works too. 
I was really surprised and a bit confused because [there are](https://github.com/marcello3d/node-mongolian/blob/master/lib/collection.js#L83-92) special checks for params.

**Comment by yorkie** [comment]
@fend25 
It's up to u, I think it's very simple ,then of course u can write these 2 bool in the 1st parm, the very very important thing is your codes is work absolutely, right? 
^.^
