### ISSUE TITLE
Debugging Map-Reduce

### ISSUE THREAD

**Issue by reggi** [marcello3d/node-mongolian#120]
I'm struggling with debugging a map reduce statement. I got it working perfectly with multiple docs in the database. But for some reason if there's one doc it doesn't' work, I think that it's passing a string to the `reduce` `values` because it seems like I'm running a `forEach` on a string. But I have no way of checking, because apparently `console.log` doesn't work inside the `reduce` anon function. Any way of debugging this???

**Comment by reggi** [comment]
Can someone please explain to me why this doesn't work:

```
db.customers.mapReduce(
    function() {
        var shop = this.shop;
        this.tags.forEach(function(tag) {
            emit(shop, tag.tag);
        });
    },
    function(key, values) {
        var nValues = (typeof values == "string") ? [].push(values) : values;
        var results = {};
        nValues.forEach(function(value) {
            if (typeof results[value] == "undefined") results[value] = 0;
            results[value] += 1;
        });
        return results;
    }, {
        out: "tag_totals",
    }
);
```

Yet this does:

```
db.customers.mapReduce(
    function() {
        var shop = this.shop;
        this.tags.forEach(function(tag) {
            emit(shop, tag.tag);
        });
    },
    function(key, values) {
        var results = {};
        values.forEach(function(value) {
            if (typeof results[value] == "undefined") results[value] = 0;
            results[value] += 1;
        });
        return results;
    }, {
        out: "tag_totals",
        finalize: function(key, reducedValue) {
            if(typeof reducedValue == "string"){
                var x = {};
                x[reducedValue] = 1;
                return x;
            }else{
                return reducedValue;
            }
        }    
    }
);
```

I do understand this is a mongo thing and not specific to Mongolian, because I'm testing in the console. But seriously what gives?!

**Comment by reggi** [comment]
I'm really perplexed as to why I can't use any global / scope variables within my mapReduce, like console.log or require / underscore. I'l love an explanation! :8ball:

**Comment by marcello3d** [comment]
As far as I know, mapReduce code is run on the server, so it doesn't have access to anything from node.js. You should ask these questions on a mongodb forum.
