### ISSUE TITLE
How to find() items by _id

### ISSUE THREAD

**Issue by qharlie** [marcello3d/node-mongolian#18]
Using find( { _id: 'fabfba4db11fe35000000000' } )  seems not to be working , and I can find ObjectId anywhere so that I can say

find( { _id: ObjectId('fabfba4db11fe35000000000') } ) 

?

**Comment by marcello3d** [comment]
You can use:
    var ObjectID = require("mongolian").ObjectID
Then you can do:
    new ObjectID('fabfba4db11fe35000000000')

This is currently based off the mongodb native code, though it may change/be cleaned up in the future. It definitely needs to be added to the documentation!

**Comment by romanmt** [comment]
This doesn't work for me. Am I doing something wrong? 

> var ObjectID = require("mongolian").ObjectID;
> new ObjectID('fabfba4db11fe35000000000');
> TypeError: undefined is not a function
>     at CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
>     at [object Context]:1:1
>     at Interface.<anonymous> (repl.js:171:22)
>     at Interface.emit (events.js:64:17)
>     at Interface._onLine (readline.js:153:10)
>     at Interface._line (readline.js:408:8)
>     at Interface._ttyWrite (readline.js:585:14)
>     at ReadStream.<anonymous> (readline.js:73:12)
>     at ReadStream.emit (events.js:81:20)
>     at ReadStream._emitKey (tty_posix.js:307:10)

It looks like Object Id is undefined.

> typeof(ObjectId);
> 'undefined'

Thanks, 
Matt

**Comment by qharlie** [comment]
I get the same, I see that it _should_ be  exported in server.js

Object.keys(bson).forEach(function(key) { exports[key] = bson[key] })

but for some reason it doesn't seem to be working.

**Comment by Charuru** [comment]
Same problem here

**Comment by marcello3d** [comment]
This is very bizarre. Changing exports to MongolianServer fixes it (I could have sworn this used to work). I'm also going to rename ObjectID to ObjectId to make it more in line with the mongo shell. Since it apparently wasn't working, I hope this isn't too big of a deal.

**Comment by cyle** [comment]
sooo how does this work?

I tried 
collection.findOne({ '_id': ObjectId(id_string) });
collection.findOne({ '_id': new ObjectId(id_string) });
and
var oid = new ObjectId(id_string);
collection.findOne({ '_id': oid });

none of them work. help please?

**Comment by marcello3d** [comment]
Mongolian DeadBeef is asynchronous, so findOne() won't return anything, and you will need to pass a callback:
    collection.findOne({ _id: new ObjectId(id_string) }, function(error, document) {
        if (error) { /\* error handling */ }
        // ... do something with document
    })

This is the primary difference between the mongo shell and Mongolian DeadBeef (perhaps I should make that clearer in the documentation), but is standard affair for Node.js.

If you're already doing that, are you sure id_string is a valid mongo-style object id hex string? Where are you getting your id_string value from, what does it look like?

**Comment by cyle** [comment]
yeah the id_string is a string of the object's _id hex. it looks like 4dc9a15e1e4cface247756c1, as I suspect it should. and I'm doing it with the async callback, I just didn't include it in the above example. it doesn't give me an error string, it doesn't get that far; the interpreter just throws a crash error on this line:

collection.findOne({ _id: new ObjectId(id_string) }, function(error, document) {

pointing to the "new ObjectId(id_string)"

TypeError: undefined is not a function
    at CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)

which is why I tried ObjectId() without the "new" before it, but it throws a similar error.

I even included the 
var ObjectId = require('mongolian').ObjectId; 
at the top of my js file.

**Comment by cyle** [comment]
did you fix this issue recently and publish it to npm? I tried updating via npm. should I recompile mongolian from source?

**Comment by marcello3d** [comment]
Aha, that would be it. It hasn't been published to NPM yet. I plan to do so soon, but "compiling" from source should be fine.

**Comment by marcello3d** [comment]
Ok, this is in v0.1.9 and now on npm.

**Comment by cyle** [comment]
It works now after running npm update. Thanks a lot for the quick response! I'm a big fan of this module.
