### ISSUE TITLE
Limits not working

### ISSUE THREAD

**Issue by xcoderzach** [marcello3d/node-mongolian#2]
The following code will call forEach for as many "things" as there are in the database, not 5

it recursively calls saveThing 10 times and then runs a query with limit 5 and forEaches the result, toArray also does not respect the limit property. 

```
var Mongolian = require("mongolian")
  , server = new Mongolian()
  , db = server.db("awesome")
  , collection = db.collection("things") 
  , i = 0
  , saveThing 

saveThing = function(done) {
  if(i < 10) {
    collection.insert({title:"w00t" + i, awesome:true}, function() { saveThing(done) })
    i++
  } else {
    done()
  }
}

saveThing(function() {
  var cursor = collection.find({awesome:true}).limit(5)
  i = 0
  cursor.forEach(function(err, item) {
    console.log(i++)
  }) 
}) 
```

**Comment by marcello3d** [comment]
Thanks for the report, limits are implemented client side (e.g. in mongolian deadbeef), but it looks like I missed a step here.

**Comment by marcello3d** [comment]
Ok, this should be fixed now.
