### ISSUE TITLE
collection.count() limiting results to 1000 ?

### ISSUE THREAD

**Issue by qharlie** [marcello3d/node-mongolian#23]
I have a collection with 5000 rows , but I'ts limiting it to 1000 results ?  Is this a mongo limitation, how can I change this ?

**Comment by marcello3d** [comment]
Can you provide a code sample? There used to be some limit bugs in an early version, but they should have been fixed a while back.

**Comment by qharlie** [comment]
Argh my bad, I've been testing a bunch of stuff and it must have gotten reset back to 0, it works fine sorry.
