### ISSUE TITLE
You want to update to 0.9.4-4 of the mongodb

### ISSUE THREAD

**Issue by christkv** [marcello3d/node-mongolian#24]
Hi Marcello

you want to use the 0.9.4-4 version of the node-mongodb-native driver as there is a BAD bug in the binary bson type serialization/deserialization that will basically write corrupt objects to the db if you use the gridfs stuff.

Cheers

**Comment by marcello3d** [comment]
Does it affect the non-native javascript serializer? I've not seen any problems with gridfs on mongolian deadbeef (I wrote the whole gridfs implementation from scratch—only the BSON serialization aspect of node-mongodb-native is used).

**Comment by christkv** [comment]
yes it does, basically you won't be able to read any file written by another language lib or write a compatible one.

**Comment by ghost** [comment]
I think I'm encountering this issue. Attempting to write jpg objects to gridfs, but nothing going into fs.chunks. The object is created, just 0 BinData.

**Comment by christkv** [comment]
I would suggest you try the mongo driver directly have a look at the examples in 

https://github.com/christkv/node-mongodb-native/blob/master/test/gridstore/grid_store_file_test.js

Also make sure you are using node 0.4.X not 0.5.pre

Cheers

**Comment by marcello3d** [comment]
coreyecviohe: can you gist your code you're using to write the file out? Mongolian DB doesn't use any of the node-mongodb-native gridfs code.

**Comment by ghost** [comment]
```
    // Code
    file = gridfs.create({
        filename: newFileName,
        contentType: 'image/jpg',
        metadata: { userId: id }
    })
    stream = file.writeStream()
    fileLocation = '/tmp/'+newFileName
    fs.createReadStream(fileLocation).pipe(stream)
```

This is it. It works fine with mongodb@0.9.4, mongolian@0.1.8; but mongodb@0.9.4-5, mongolian@0.1.9, I'll get empty BinData.

**Comment by marcello3d** [comment]
Out of curiosity, have you tried mongodb@0.9.4 + mongolian@0.1.9 or mongodb@0.9.4-5 + mongolian@0.1.8? It would be helpful to track down which version switch is causing the problem (if not both).

**Comment by marcello3d** [comment]
Ok, I just verified that it's mongodb@0.9.4-4 (and -5, but not -3) + mongolian@0.1.9 that causes the problem (the standard mongolian tests fail).

**Comment by ghost** [comment]
Ah, sorry I didn't get back earlier. Yes, I think 0.9.4-4 was the main culprit. I had a friend who was using the latest 0.9.4-5 and reported failure as well, but I didn't confirm it; I just rolled back to 0.9.4/0.1.8 to get everything working again. Glad to see the issues were identified, no rush though. Awesome job on this npm btw, really great work!

**Comment by marcello3d** [comment]
Ok, I've tracked down the cause problem. In order to work around a bug in mongodb-native, where the Buffer in the Binary is larger than the data (it starts with 256 bytes), I've been reading the Binary.position field, but this field seems to be zero now. I'm kind of at a loss as to why this is happening (none of the diffs on binary_parser.js or binary.js seem to affect this), but I'll dig into it more.

**Comment by marcello3d** [comment]
Ok, I've tracked down the regression in mongodb-native and submitted a pull request: https://github.com/christkv/node-mongodb-native/pull/262 Sneaky!
