### ISSUE TITLE
query the database from the client?

### ISSUE THREAD

**Issue by Taler-zz** [marcello3d/node-mongolian#25]
I'm trying to query the database from the client sorta like this:

```
     var query = {
       "selector":{
         "type": "comment"
       },
       "options":{
         "sort": {
           "t":-1
         }
       }
     }
     db(query, function (data) {
       renderComments (data);
     });
```

Is there a recommended way of passing this kind of query from the client?

I'm thinking about using RPC or something.

**Comment by marcello3d** [comment]
If you're just trying to do a regular find query, you can use the find command to get a cursor:

```
var cursor = db.collection("foo").find({ type:"comment" }).sort({ t:-1 })
```

Then with the cursor you can convert the results to an array:

```
cursor.toArray(function(error, array) { 
    if (error || !array) { ... handle mongo db/io/etc error ... }
    else { renderComments(array) }
})
```

Is this what you're asking, or am I misunderstanding?

**Comment by Taler-zz** [comment]
Nevermind, this question is nonsense. :)
