### ISSUE TITLE
How to connect mongo sharding?

### ISSUE THREAD

**Issue by khemmac** [marcello3d/node-mongolian#28]
Here's my log

mongo://192.168.254.191:30001: Connected
mongo://192.168.254.191:30001: Connected
Finished scanning... primary? no
# uncaughtException : Error: Could not connect to primary: Error: Server Error: { '$err': 'assertion s/config.h:108', code: 0 }

   at EventEmitter.<anonymous> (/home/user/Documents/www/myApplication/node_modules/mongolian/lib/server.js:117:49)
   at EventEmitter.g (events.js:143:14)
   at EventEmitter.emit (events.js:81:20)
   at /home/user/Documents/www/myApplication/node_modules/mongolian/lib/server.js:75:34
   at /home/user/Documents/www/myApplication/node_modules/mongolian/lib/db.js:62:13
   at /home/user/Documents/www/myApplication/node_modules/mongolian/lib/util.js:19:18
   at [object Object].next (/home/user/Documents/www/myApplication/node_modules/mongolian/lib/cursor.js:159:9)
   at /home/user/Documents/www/myApplication/node_modules/mongolian/lib/cursor.js:163:18
   at /home/user/Documents/www/myApplication/node_modules/mongolian/lib/util.js:19:18
   at /home/user/Documents/www/myApplication/node_modules/mongolian/lib/cursor.js:117:9
Finished scanning... primary? no

**Comment by marcello3d** [comment]
I have not personally tested out mongolian with a sharding setup, so I can't speak to whether it works. From what I understand, sharding should work just like a regular replicated server. The particular message is a server error, meaning there is some kind of configuration problem.

A quick google search gives me this mailing list thread: https://groups.google.com/forum/#!topic/mongodb-user/N_dkPNS1Eq8

Does that help?

**Comment by niranpr** [comment]
Any updates here..? I also got a problem on using sharding with mongolian as well.. :(

**Comment by marcello3d** [comment]
niranpr: what is your problem? Can you give more details?

**Comment by niranpr** [comment]
When I setup sharing in mongodb, the mongolian seemed not to connect to primary db

**Comment by marcello3d** [comment]
It would be helpful to know things such as: What version of mongolian do you have installed? What version of mongodb are you using? Have you successfully used mongolian in a non-shared setup? What does your mongodb setup look like? How are you connecting to it with mongolian?

Can you include some sample code of what's not working for you? What errors are you getting in your callbacks? What logging is printed out to the console?

**Comment by niranpr** [comment]
Will ask my team to provide information and will post here asap.
Thank for your prompt response. :)

**Comment by marcello3d** [comment]
Is this still an issue?

**Comment by mahan** [comment]
Yes. I get the following error when i try to connect to a mongos (as opposed to mongod) process that is my shared clusters frontend:

[debug] mongo://192.168.0.216:27017: Connected
[debug] Finished scanning... primary? no
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Server Error: assertion s/config.h:119',
  result: { '$err': 'assertion s/config.h:119', code: 0 } }

It seems as if this error message might be reported in the scanServer() method in server.js around the lines:
                self.log.debug("Finished scanning... primary? " + (self._primary || 'no'))
                self._replicaSet.emit('scanned', scanErrors)

**Comment by mahan** [comment]
Update: While playing around with this issue i noticed that I could get a connection to mongos by inserting this code at the top of the function scanServer(server) in server.js:
        self._primary = server
        self.log.info(server+": Connected to primary")
        self._replicaSet.emit('primary',server)  
        return

(code copied from below in that same function, on success)
I don't know if it's good to do so, but I figured that when using mongos it acts like a "mongod proxy" and hides the sharding details from the app, so basically the mongos becomes the "master" for the applications viewpoint.

**Comment by yosefd** [comment]
I think that the correct fix for that should be in the following line:

self.db('').runCommand({ ismaster: 1 }, function (error, result) {

change it to:

self.db('admin').runCommand({ ismaster: 1 }, function (error, result) {

the db should be 'admin'. After this, the stuff worked for me.
ismaster command supposed to return true from mongos and this what happens indeed.
