### ISSUE TITLE
Is there a way to do Upserts

### ISSUE THREAD

**Issue by clintberry** [marcello3d/node-mongolian#3]
Is there a way to do upserts in Mongolian? 

p.s. I love the simplicity of what you have done.

**Comment by clintberry** [comment]
Nevermind, I see it in the code now. Thanks.

**Comment by marcello3d** [comment]
It should be the same as on the mongodb shell:
http://www.mongodb.org/display/DOCS/Updating#Updating-UpsertswithModifiers

Granted, maybe this is a good case for diverging from their CLI, as I don't think this is that obvious.
