### ISSUE TITLE
Memory Spike help?

### ISSUE THREAD

**Issue by bingomanatee** [marcello3d/node-mongolian#44]
I am writing a series of updates that updates a collection with a large number of integers: 

//image rows:  5632 image.cols: 11520

```
       for (var i = 0; i < i_limit; i += scale)
            for (var j = 0; j < j_limit; j += scale) {
                var heights = _chunk(image_data, i, i + scale, j, j + scale); // returns a 128 x 128 nested array of ints
                var query = {min_image_i: i, min_image_j: j, image: image._id};
                var set_heights = {"$set": {heights: heights}};
                mit_model.update(query, gcb, set_heights); // note - my custom model switches the order
```

// of the parameters a bit. 
                }

I get around a thousand loops before it crashes. 

Is there any way I can flush something to improve performance?

**Comment by marcello3d** [comment]
It should all be written/flushed out to the network immediately when you use
model.update _without a callback_. If you set a callback, it will send
getLastErrors and keep track of responses which will definitely add to the
memory usage.

Perhaps a Node.js network write buffer limitation? Have you tried increasing
its ram limit? What exactly is the crash?

If that doesn't help you might have to look into breaking up the work into
pieces. This might be partially alleviated with connection pooling, but I'm
not certain without more information.

**Comment by bingomanatee** [comment]
My research shows me that the Apple people prefer to do your thinking for you in the area of ram management. I'm going to try a more frequent fsync to lower the overhead of mongo's ram cache and play with journaling.

I have started breaking this into smaller chunks - saving whole rows of data then putting off the subchunking of rows by column - it makes the slow process even slower but it at least makes it easier to not lose all my work when I crash... :D

**Comment by marcello3d** [comment]
Good to hear. Do you think there is a Mongolian DB bug here, or at least
something that Mongolian could improve?

**Comment by bingomanatee** [comment]
http://wonderlandlabs.com/wll_drupal/os/node/gigs.html documents the problems and the solutions I found to get my data streaming nicely. The big determinant for me was that timeouts are no substitute for nextTick in node. 

That being said, you might investigate independently what happens to memory / caches when you insert multiple records of large chunks of data - say 100,000 key/value pairs - in a single non-event segmented loop.
