### ISSUE TITLE
How do you connect to a remote database?

### ISSUE THREAD

**Issue by bingomanatee** [marcello3d/node-mongolian#48]
The "documentation" doesn't describe setting up a remote server. Also, Mongolian()'s lone parameter doesn't appear to be used anywhere??

**Comment by bingomanatee** [comment]
figured it out ...

new Mongolian({host: MONGODB_SERVER_NAME, port: MONGODB_PORT}). 

Still...

Would you like me to work up your doc wiki on github? 

Dave

**Comment by marcello3d** [comment]
It should be described in the "Connections and Authentication" section of the Readme. Definitely welcome suggestions on making it clearer. 

Here is an excerpt:

```
// Create a server with a specific host/port
var server = new Mongolian("mongo.example.com:12345")

// Supported connection url format: [mongo://][username:password@]hostname[:port][/databasename]
// Use uri-encoding for special characters in the username/password/database name
```

The bracketed parts are optional.

```
// Database/auth shorthand (equivalent to calling db() and auth() on the resulting server)
var db = new Mongolian("mongo://username:password@mongo.example.com:12345/database")

// Connecting to replicasets:
var server = new Monglian(
    "server1.local",
    "server2.local",
    "server3.local:27018"
)
```

The {host:host,port:port} syntax is also supported but it might go away.
