### ISSUE TITLE
How do you connect to a remote database -- with authentication?

### ISSUE THREAD

**Issue by bingomanatee** [marcello3d/node-mongolian#49]
Don't see any hooks for auth - am I missing something?

**Comment by marcello3d** [comment]
It works the same way as on the mongo db shell:

```
db.auth(username, password)
```

You can read more about it in the Readme under the "Connections and Authentication" section.

**Comment by ghost** [comment]
Here is my code to connect:
Data.prototype.getTable = function (server_,db_,usr_,pass_, tableName_) {

```
var server1 = new Mongolian(server_, {
log: {
     debug: function(message){ }
    ,info:  function(message){ }
    ,warn:  function(message){ console.log(message) }
    ,error: function(message){ console.log(message) }
    }
});

var db1 = server1.db(db_)
//db1.getMongo().setSlaveOk()

db1.auth(usr_,pass_)
//table
var table = db1.collection(tableName_);
return table;
```

}

**Comment by simpleseeker** [comment]
I think authentication stop working after mongolian moved off of mongodb-native. I got it working again after I down version my node-mongolian.
