### ISSUE TITLE
How to lower log level

### ISSUE THREAD

**Issue by ghost** [marcello3d/node-mongolian#54]
The driver is noisy. How do I lower the logging level, to warning and errors only?

**Comment by marcello3d** [comment]
Check out the Logging section of the readme:

By default, Mongolian logs to console.log, but you can override this by specifying your own log object (any object that
provides `debug`, `info`, `warn`, and `error` methods):

```
new Mongolian({
    log: {
        debug: function(message) { ... },
        info: function(message) { ... },
        warn: function(message) { ... },
        error: function(message) { ... }
    }
})
```

**Comment by ghost** [comment]
I saw the docs, they are good, but I assumed there was something like setLogLevel.

I know have:
var server1 = new Mongolian(serverUrl);

If I set the log level, how do I tell it what server to connect to?

**Comment by marcello3d** [comment]
You can do:

```
new Mongolian(serverUrl, {
    log: {
        debug: function(message) { ... },
        info: function(message) { ... },
        warn: function(message) { ... },
        error: function(message) { ... }
    }
})
```

**Comment by ghost** [comment]
thx for your help! I'll let you know when we go live, should be soon.
