### ISSUE TITLE
node 0.4.4 crashes with latest mongolian

### ISSUE THREAD

**Issue by ippa** [marcello3d/node-mongolian#7]
Seems like mongolian is trying to use a console.debug() which isn't defined in latest vanilla node.

> console
> { log: [Function],
>   info: [Function],
>   warn: [Function],
>   error: [Function],
>   dir: [Function],
>   time: [Function],
>   timeEnd: [Function],
>   trace: [Function],
>   assert: [Function] }

**Comment by marcello3d** [comment]
What do you think mongolian should use for logging? I've personally switched to log4js but I'm not sure if I should add that dependency to mongolian db itself.

**Comment by ippa** [comment]
as you say, adding depencies feels bad. especially for a lib with a "less is more"-mantra :). Just use the builtin console-methods? console.log, console.warn, console.error etc

**Comment by marcello3d** [comment]
logging tweaks (closed by dabbdcd4f57e4fb998fca1cbc2e80db18ea6be5c)
