### ISSUE TITLE
Cannot remove using ObjectID

### ISSUE THREAD

**Issue by demian85** [marcello3d/node-mongolian#81]
Please explain why I cannot remove an object by its id.

```
var util = require('util'),
    Mongolian = require('mongolian');

var ObjectId =  Mongolian.ObjectId ;
var db = new Mongolian('mongo://localhost/nsmetrics');

var collection = db.collection('proxy');
collection.find().toArray(function(err, res) {
    console.log(res.length);
    collection.remove({_id: new ObjectId(res[0]._id.toString())}, function(err) {
        if (err) throw err;
        db.server.close();
    });
})
```

That always prints the same length. I still don't know how to use that damn ObjectID.

Thanks.

**Comment by marcello3d** [comment]
This looks like a bug, but I'll need more information to understand it.

What version of mongolian and node.js are you using? How big is the collection?

Try printing out the structure of `res` with `console.dir(res)` (or `console.dir(res[0])`) to see if anything looks odd. Try adding a log statement in the remove callback to see if your callback is even triggered.

Regarding ObjectId, your code example should work, although it'd be more efficient to do: `collection.remove({ _id:res[0]._id }, ... )` (If changing to that fixes it, please let me know.)

**Comment by marcello3d** [comment]
This is probably related to GH-83. Try upgrading to 0.1.17 and see if that resolves the problem.
