### ISSUE TITLE
findAndModify override the entire row

### ISSUE THREAD

**Issue by norman784** [marcello3d/node-mongolian#88]
Im trying just to update a row, but when I "update" it get replaced by the new object and not just update the fields that i want

``` javascript
campaing.findAndModify({
          query: {
            id : req.params['id']
          },
          update: {
            subject:      req.param('subject'),
            from:         req.param('from'),
            reply_to:     req.param('from'),
            body:         req.param('body')
          },
          new: true
        }, function(err, data){
          //
        })
```

The document has more than this 4 cols, but when I update only those 4 remain, the other seems to be deleted!

**Comment by marcello3d** [comment]
I think you need to use $set notation to do a partial update. Check out the documentation here:
http://www.mongodb.org/display/DOCS/Updating
http://www.mongodb.org/display/DOCS/findAndModify+Command
