### ISSUE TITLE
why tell me '[debug] Finished scanning... primary? mongo://10.100.200.55:30000'

### ISSUE THREAD

**Issue by altila** [marcello3d/node-mongolian#92]
http.createServer(function(request,response){

```
var start = new Date().getTime();
var Mongolian = require('mongolian');
var server = new Mongolian("10.100.200.55:30000");
var db = server.db("BgTongji");
var advert = db.collection("advertising");
var goodsVideo = db.collection("goods_video");
//查询数据
advert.find().limit(5).toArray(function(err,array){
    console.dir(array);
});
```

}).listen(8164, "10.100.200.29");
console.log('Server running at http://10.100.200.29:8164/');

why tell me :
[debug] mongo://10.100.200.55:30000: Connected
[debug] mongo://10.100.200.55:30000: Initialized as primary
[info] mongo://10.100.200.55:30000: Connected to primary
[debug] Finished scanning... primary? mongo://10.100.200.55:30000
undefined
can you help me?

**Comment by marcello3d** [comment]
It's perfectly normal to have that line (it's just a debug statement).

When you have a replica set, Mongolian builds a list of potential servers and then determines which is the primary server to connect to.

If array is undefined, you should print out `err` and see why. In fact, you should always check the error parameter in a node.js callback.
